In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[96, 79],
       [41, 98],
       [67, 94],
       [99, 22],
       [89, 19],
       [40, 85],
       [11, 39],
       [97, 98],
       [59, 34],
       [61, 93]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

C:\Anaconda3\envs\morti_os_suite\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
scaler_model.transform(data)

array([[0.96590909, 0.75949367],
       [0.34090909, 1.        ],
       [0.63636364, 0.94936709],
       [1.        , 0.03797468],
       [0.88636364, 0.        ],
       [0.32954545, 0.83544304],
       [0.        , 0.25316456],
       [0.97727273, 1.        ],
       [0.54545455, 0.18987342],
       [0.56818182, 0.93670886]])

In [10]:
scaler_model.fit_transform(data)

C:\Anaconda3\envs\morti_os_suite\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.96590909, 0.75949367],
       [0.34090909, 1.        ],
       [0.63636364, 0.94936709],
       [1.        , 0.03797468],
       [0.88636364, 0.        ],
       [0.32954545, 0.83544304],
       [0.        , 0.25316456],
       [0.97727273, 1.        ],
       [0.54545455, 0.18987342],
       [0.56818182, 0.93670886]])

In [12]:
import pandas as pd

In [13]:
my_data = np.random.randint(0,101,(50,4))

In [14]:
my_data

array([[ 52,   0,  90,  92],
       [ 27,  94,  62,   8],
       [ 44,   1,  62,  67],
       [ 76,  61,  86,   3],
       [ 19,  46,   3,  20],
       [ 82,  60,  78,  79],
       [ 32,   5,  98,  66],
       [ 60,   0,  98,  15],
       [ 66,  51,  57,   2],
       [ 35,  29,  41,  70],
       [ 13,  15,  52,  39],
       [100,  65,  76,  70],
       [ 90,  89,  75,  90],
       [ 97,  48,  13,  90],
       [ 27,  69,  30,  13],
       [ 64,  14,  31,  41],
       [ 86,  80,  41,  71],
       [ 52,  10,   5,   5],
       [ 49,  22,   7,  38],
       [ 22,  52,   6,  54],
       [ 10,  74,  22,  42],
       [ 88,  32,  32,   9],
       [ 48,  55,  77,  45],
       [ 57,  50,  11,  94],
       [ 40,  25,  14,  17],
       [ 16,  58,  63,  88],
       [ 63,  18,  56,   9],
       [  4,  45,  19,  82],
       [ 16,  27,   9,  29],
       [ 98,  31,  12,  40],
       [ 78,  57,  73,  63],
       [ 55,  77,  66,  97],
       [ 90,  52,  15,  97],
       [ 78,  51,  62,   4],
       [ 62,  

In [18]:
data = pd.DataFrame(data=my_data,columns = ['f1','f2','f3','label'])

In [19]:
data

f1  f2  f3  label
0    52   0  90     92
1    27  94  62      8
2    44   1  62     67
3    76  61  86      3
4    19  46   3     20
5    82  60  78     79
6    32   5  98     66
7    60   0  98     15
8    66  51  57      2
9    35  29  41     70
10   13  15  52     39
11  100  65  76     70
12   90  89  75     90
13   97  48  13     90
14   27  69  30     13
15   64  14  31     41
16   86  80  41     71
17   52  10   5      5
18   49  22   7     38
19   22  52   6     54
20   10  74  22     42
21   88  32  32      9
22   48  55  77     45
23   57  50  11     94
24   40  25  14     17
25   16  58  63     88
26   63  18  56      9
27    4  45  19     82
28   16  27   9     29
29   98  31  12     40
30   78  57  73     63
31   55  77  66     97
32   90  52  15     97
33   78  51  62      4
34   62  15  82     31
35   57  87  65     76
36    4  94  74     25
37    8  11   3      7
38   55  96  13     60
39   37  29  53     43
40   44   5  91     61
41   98  42  80     55
42   13   4  38     64
43   52  16   2      1
44   10  31  78     27
45   24  54  91     39
46   47  90  42     98
47   82  86  31     39
48   70  35  94     56
49   19  44  56     32

In [20]:
X = data[['f1','f2','f3']]

In [22]:
y = data['label']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 101)

In [27]:
X_train.shape

(35, 3)

In [28]:
X_test.shape

(15, 3)